### ISSUE TITLE
making package compatible with latest updates of blade-icons

### ISSUE THREAD

**Issue by swapnilsarwe** [Hasnayeen/blade-eva-icons#4]
Hey @Hasnayeen ,

Are you planning to maintain this package? 
If yes, I will upgrade this package to support `blade-icons:^1.0` & also add config support to be compatible with the latest updates.

**Comment by Hasnayeen** [comment]
@swapnilsarwe yes

**Comment by swapnilsarwe** [comment]
@Hasnayeen - you upgrading it or you are OK with me sending a PR for the same?

**Comment by Hasnayeen** [comment]
@swapnilsarwe yes would appreciate a PR, thank you
